// components/DayPicker.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'

import { CalendarDays, ChevronLeft, ChevronRight } from 'lucide-vue-next'

import { Button } from '@/components/ui/button'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'
import { cn } from '@/lib/utils'

const DAYS_PER_PAGE = 16
const TOTAL_DAYS = 31
const TOTAL_PAGES = Math.ceil(TOTAL_DAYS / DAYS_PER_PAGE)

const props = withDefaults(
  defineProps<{
    modelValue?: number | null
    id?: string
    placeholder?: string
    disabled?: boolean
    minDay?: number
    maxDay?: number
    triggerClass?: HTMLAttributes['class']
  }>(),
  {
    modelValue: null,
    id: undefined,
    placeholder: 'Wybierz dzień',
    disabled: false,
    minDay: 1,
    maxDay: 31,
    triggerClass: undefined,
  },
)

const emit = defineEmits<{
  'update:modelValue': [value: number]
}>()

const open = ref(false)
const page = ref(0)

function getDaysForPage(pageIndex: number): number[] {
  const start = pageIndex * DAYS_PER_PAGE + 1
  const end = Math.min(start + DAYS_PER_PAGE - 1, TOTAL_DAYS)
  return Array.from({ length: end - start + 1 }, (_, i) => start + i)
}

function isDayDisabled(day: number): boolean {
  return day < props.minDay || day > props.maxDay
}

function isDaySelected(day: number): boolean {
  return props.modelValue === day
}

function handleDaySelect(day: number) {
  emit('update:modelValue', day)
  open.value = false
}

const pageLabel = computed(() =>
  page.value === 0 ? 'Dni 1–16' : 'Dni 17–31',
)

const todayDay = computed(() => new Date().getDate())

const todayDisabled = computed(() => {
  const t = todayDay.value
  return t < props.minDay || t > props.maxDay
})

function selectToday() {
  const t = todayDay.value
  if (t < props.minDay || t > props.maxDay) return
  page.value = t <= 16 ? 0 : 1
  handleDaySelect(t)
}

const hasValue = computed(() => {
  const v = props.modelValue
  return (
    v != null &&
    Number.isFinite(v) &&
    v >= props.minDay &&
    v <= props.maxDay
  )
})

watch(open, (isOpen) => {
  if (!isOpen) return
  const v = props.modelValue
  if (
    v != null &&
    Number.isFinite(v) &&
    v >= 1 &&
    v <= TOTAL_DAYS
  ) {
    page.value = v <= 16 ? 0 : 1
  }
})
</script>

<template>
  <Popover v-model:open="open">
    <PopoverTrigger as-child>
      <Button
        :id="id"
        type="button"
        variant="outline"
        role="combobox"
        :aria-expanded="open"
        :disabled="disabled"
        :class="
          cn(
            'w-full min-w-0 justify-start text-left font-normal',
            !hasValue && 'text-muted-foreground',
            triggerClass,
          )
        "
      >
        <CalendarDays class="mr-2 size-4 shrink-0" />
        <span class="min-w-0 truncate">{{
          hasValue ? String(modelValue) : placeholder
        }}</span>
      </Button>
    </PopoverTrigger>
    <PopoverContent class="w-60 p-0" align="start">
      <div class="p-3">
        <div class="mb-3 flex items-center justify-between">
          <Button
            type="button"
            variant="ghost"
            size="icon"
            class="size-7"
            :disabled="page === 0"
            aria-label="Poprzednia strona"
            @click="page = Math.max(0, page - 1)"
          >
            <ChevronLeft class="size-4" />
          </Button>
          <span class="text-sm font-medium">{{ pageLabel }}</span>
          <Button
            type="button"
            variant="ghost"
            size="icon"
            class="size-7"
            :disabled="page === TOTAL_PAGES - 1"
            aria-label="Następna strona"
            @click="page = Math.min(TOTAL_PAGES - 1, page + 1)"
          >
            <ChevronRight class="size-4" />
          </Button>
        </div>
        <div class="grid grid-cols-4 gap-2">
          <Button
            v-for="day in getDaysForPage(page)"
            :key="day"
            type="button"
            :variant="isDaySelected(day) ? 'default' : 'ghost'"
            size="sm"
            class="h-9 w-full"
            :disabled="isDayDisabled(day)"
            @click="handleDaySelect(day)"
          >
            {{ day }}
          </Button>
        </div>
        <div class="mt-3 border-t border-border pt-3">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            class="w-full"
            :disabled="todayDisabled"
            @click="selectToday"
          >
            Dzisiejszy dzień
          </Button>
        </div>
      </div>
    </PopoverContent>
  </Popover>
</template>

// .knowledge/day-picker.tsx
'use client'

import * as React from 'react'
import { CalendarDays, ChevronLeft, ChevronRight } from 'lucide-react'

import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'

interface DayPickerProps {
  value?: number
  onChange?: (day: number) => void
  placeholder?: string
  disabled?: boolean
  className?: string
  minDay?: number
  maxDay?: number
}

export function DayPicker({
  value,
  onChange,
  placeholder = 'Select day',
  disabled = false,
  className,
  minDay = 1,
  maxDay = 31,
}: DayPickerProps) {
  const [open, setOpen] = React.useState(false)
  const [page, setPage] = React.useState(0)

  const DAYS_PER_PAGE = 16
  const TOTAL_DAYS = 31
  const TOTAL_PAGES = Math.ceil(TOTAL_DAYS / DAYS_PER_PAGE)

  const getDaysForPage = (pageIndex: number) => {
    const start = pageIndex * DAYS_PER_PAGE + 1
    const end = Math.min(start + DAYS_PER_PAGE - 1, TOTAL_DAYS)
    return Array.from({ length: end - start + 1 }, (_, i) => start + i)
  }

  const handleDaySelect = (day: number) => {
    onChange?.(day)
    setOpen(false)
  }

  const isDayDisabled = (day: number) => {
    if (day < minDay || day > maxDay) return true
    return false
  }

  const isDaySelected = (day: number) => {
    return value === day
  }

  const getOrdinalSuffix = (day: number) => {
    if (day > 3 && day < 21) return 'th'
    switch (day % 10) {
      case 1:
        return 'st'
      case 2:
        return 'nd'
      case 3:
        return 'rd'
      default:
        return 'th'
    }
  }

  const formatDay = (day: number) => {
    return `${day}${getOrdinalSuffix(day)}`
  }

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          disabled={disabled}
          className={cn(
            'w-[180px] justify-start text-left font-normal',
            !value && 'text-muted-foreground',
            className,
          )}
        >
          <CalendarDays className="mr-2 h-4 w-4" />
          {value ? formatDay(value) : placeholder}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[240px] p-0" align="start">
        <div className="p-3">
          <div className="flex items-center justify-between mb-3">
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7"
              onClick={() => setPage((p) => Math.max(0, p - 1))}
              disabled={page === 0}
              aria-label="Previous page"
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <span className="text-sm font-medium">
              {page === 0 ? 'Days 1-16' : 'Days 17-31'}
            </span>
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7"
              onClick={() => setPage((p) => Math.min(TOTAL_PAGES - 1, p + 1))}
              disabled={page === TOTAL_PAGES - 1}
              aria-label="Next page"
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
          <div className="grid grid-cols-4 gap-2">
            {getDaysForPage(page).map((day) => (
              <Button
                key={day}
                variant={isDaySelected(day) ? 'default' : 'ghost'}
                size="sm"
                className={cn('h-9 w-full')}
                disabled={isDayDisabled(day)}
                onClick={() => handleDaySelect(day)}
              >
                {day}
              </Button>
            ))}
          </div>
          <div className="mt-3 pt-3 border-t">
            <Button
              variant="ghost"
              size="sm"
              className="w-full"
              onClick={() => {
                const today = new Date().getDate()
                if (today >= minDay && today <= maxDay) {
                  setPage(today <= 16 ? 0 : 1)
                  handleDaySelect(today)
                }
              }}
              disabled={(() => {
                const today = new Date().getDate()
                return today < minDay || today > maxDay
              })()}
            >
              Today&apos;s Day
            </Button>
          </div>
        </div>
      </PopoverContent>
    </Popover>
  )
}
