// components/YearPicker.vue
<script setup lang="ts">
import type { HTMLAttributes } from 'vue'

import { CalendarDays, ChevronLeft, ChevronRight } from 'lucide-vue-next'
import { computed, ref, watch } from 'vue'
import { cn } from '~/lib/utils'
import type { ButtonVariants } from './ui/button'

const YEARS_PER_PAGE = 12

type Props = {
  id?: string
  minYear?: number
  maxYear?: number
  placeholder?: string
  disabled?: boolean
  class?: HTMLAttributes['class']
  triggerVariant?: ButtonVariants['variant']
}

const props = withDefaults(defineProps<Props>(), {
  id: undefined,
  minYear: 1900,
  maxYear: 2100,
  placeholder: 'Wybierz rok',
  disabled: false,
  triggerVariant: 'outline',
})

const modelValue = defineModel<number | undefined>()

const open = ref(false)
const currentYear = new Date().getFullYear()

function getStartYear(y: number) {
  return Math.floor(y / YEARS_PER_PAGE) * YEARS_PER_PAGE
}

const pageStartYear = ref(getStartYear(modelValue.value ?? currentYear))

const years = computed(() =>
  Array.from({ length: YEARS_PER_PAGE }, (_, i) => pageStartYear.value + i),
)

watch([open, modelValue], () => {
  if (open.value) {
    pageStartYear.value = getStartYear(modelValue.value ?? currentYear)
  }
})

function handleYearSelect(y: number) {
  modelValue.value = y
  open.value = false
}

function handlePreviousPage() {
  pageStartYear.value -= YEARS_PER_PAGE
}

function handleNextPage() {
  pageStartYear.value += YEARS_PER_PAGE
}

function isYearDisabled(y: number) {
  return y < props.minYear || y > props.maxYear
}

function isYearSelected(y: number) {
  return modelValue.value === y
}

function isCurrentYear(y: number) {
  return y === currentYear
}

const canGoPrevious = computed(() => pageStartYear.value > props.minYear)
const canGoNext = computed(
  () => pageStartYear.value + YEARS_PER_PAGE <= props.maxYear,
)

function selectCurrentYear() {
  pageStartYear.value = getStartYear(currentYear)
  if (currentYear < props.minYear || currentYear > props.maxYear) return
  handleYearSelect(currentYear)
}

const currentYearDisabled = computed(
  () => currentYear < props.minYear || currentYear > props.maxYear,
)
</script>

<template>
  <Popover v-model:open="open">
    <PopoverTrigger as-child>
      <Button
        :id="id"
        type="button"
        role="combobox"
        :aria-expanded="open"
        aria-label="Wybierz rok"
        :variant="triggerVariant"
        :disabled="disabled"
        :class="
          cn(
            'w-[200px] justify-start text-left font-normal',
            modelValue == null && 'text-muted-foreground',
            props.class,
          )
        "
      >
        <CalendarDays class="mr-2 size-4 shrink-0" />
        <span v-if="modelValue != null">{{ modelValue }}</span>
        <span v-else>{{ placeholder }}</span>
      </Button>
    </PopoverTrigger>

    <PopoverContent class="w-[280px] p-0" align="start">
      <div class="p-3">
        <div class="mb-3 flex items-center justify-between">
          <Button
            type="button"
            variant="outline"
            size="icon-sm"
            :disabled="!canGoPrevious"
            @click="handlePreviousPage"
          >
            <ChevronLeft class="size-4" />
            <span class="sr-only">Poprzednie lata</span>
          </Button>
          <span class="text-sm font-medium">
            {{ pageStartYear }} – {{ pageStartYear + YEARS_PER_PAGE - 1 }}
          </span>
          <Button
            type="button"
            variant="outline"
            size="icon-sm"
            :disabled="!canGoNext"
            @click="handleNextPage"
          >
            <ChevronRight class="size-4" />
            <span class="sr-only">Następne lata</span>
          </Button>
        </div>

        <div class="grid grid-cols-3 gap-2">
          <Button
            v-for="y in years"
            :key="y"
            type="button"
            :variant="isYearSelected(y) ? 'default' : 'ghost'"
            size="sm"
            :disabled="isYearDisabled(y)"
            :class="
              cn(
                'h-9',
                isCurrentYear(y) &&
                  !isYearSelected(y) &&
                  'border border-primary text-primary',
              )
            "
            @click="handleYearSelect(y)"
          >
            {{ y }}
          </Button>
        </div>

        <div class="mt-3 border-t pt-3">
          <Button
            type="button"
            variant="ghost"
            size="sm"
            class="w-full"
            :disabled="currentYearDisabled"
            @click="selectCurrentYear"
          >
            Bieżący rok
          </Button>
        </div>
      </div>
    </PopoverContent>
  </Popover>
</template>

// .knowledge/year-picker.tsx
'use client'

import * as React from 'react'
import { ChevronLeft, ChevronRight, CalendarDays } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Button } from '@/components/ui/button'
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from '@/components/ui/popover'

interface YearPickerProps {
  value?: number
  onChange?: (year: number) => void
  minYear?: number
  maxYear?: number
  placeholder?: string
  disabled?: boolean
  className?: string
}

const YEARS_PER_PAGE = 12

export function YearPicker({
  value,
  onChange,
  minYear = 1900,
  maxYear = 2100,
  placeholder = 'Pick a year',
  disabled = false,
  className,
}: YearPickerProps) {
  const [open, setOpen] = React.useState(false)
  const currentYear = new Date().getFullYear()

  // Calculate the starting decade page based on value or current year
  const getStartYear = (year: number) => {
    return Math.floor(year / YEARS_PER_PAGE) * YEARS_PER_PAGE
  }

  const [pageStartYear, setPageStartYear] = React.useState(() =>
    getStartYear(value ?? currentYear),
  )

  // Generate array of years for current page
  const years = React.useMemo(() => {
    return Array.from({ length: YEARS_PER_PAGE }, (_, i) => pageStartYear + i)
  }, [pageStartYear])

  const handleYearSelect = (year: number) => {
    onChange?.(year)
    setOpen(false)
  }

  const handlePreviousPage = () => {
    setPageStartYear((prev) => prev - YEARS_PER_PAGE)
  }

  const handleNextPage = () => {
    setPageStartYear((prev) => prev + YEARS_PER_PAGE)
  }

  const isYearDisabled = (year: number) => {
    return year < minYear || year > maxYear
  }

  const isYearSelected = (year: number) => {
    return value === year
  }

  const isCurrentYear = (year: number) => {
    return year === currentYear
  }

  const canGoPrevious = pageStartYear > minYear
  const canGoNext = pageStartYear + YEARS_PER_PAGE <= maxYear

  // Reset page when popover opens
  React.useEffect(() => {
    if (open) {
      setPageStartYear(getStartYear(value ?? currentYear))
    }
  }, [open, value, currentYear])

  return (
    <Popover open={open} onOpenChange={setOpen}>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          aria-expanded={open}
          aria-label="Select a year"
          disabled={disabled}
          className={cn(
            'w-[200px] justify-start text-left font-normal',
            !value && 'text-muted-foreground',
            className,
          )}
        >
          <CalendarDays className="mr-2 h-4 w-4" />
          {value ? value : placeholder}
        </Button>
      </PopoverTrigger>
      <PopoverContent className="w-[280px] p-0" align="start">
        <div className="p-3">
          <div className="flex items-center justify-between mb-3">
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7"
              onClick={handlePreviousPage}
              disabled={!canGoPrevious}
              aria-label="Previous years"
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <span className="text-sm font-medium">
              {pageStartYear} - {pageStartYear + YEARS_PER_PAGE - 1}
            </span>
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7"
              onClick={handleNextPage}
              disabled={!canGoNext}
              aria-label="Next years"
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
          <div className="grid grid-cols-3 gap-2">
            {years.map((year) => (
              <Button
                key={year}
                variant={isYearSelected(year) ? 'default' : 'ghost'}
                size="sm"
                className={cn(
                  'h-9',
                  isCurrentYear(year) &&
                    !isYearSelected(year) &&
                    'border border-primary text-primary',
                )}
                disabled={isYearDisabled(year)}
                onClick={() => handleYearSelect(year)}
              >
                {year}
              </Button>
            ))}
          </div>
          <div className="mt-3 pt-3 border-t">
            <Button
              variant="ghost"
              size="sm"
              className="w-full"
              onClick={() => {
                setPageStartYear(getStartYear(currentYear))
                handleYearSelect(currentYear)
              }}
              disabled={currentYear < minYear || currentYear > maxYear}
            >
              Current Year
            </Button>
          </div>
        </div>
      </PopoverContent>
    </Popover>
  )
}
